server:
    port: 53101



spring:
  datasource:
    url: jdbc:mysql://120.55.42.29:3306/ak_blog?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: noneone168
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 1
    maxActive: 30
    minIdle: 5
    maxWaite: 600000
    testOnBorrow: true
    test-while-idle: true


# eurker
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}:${random.value}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka/

